Feature 2 fetisovden
SlavZ27/AnimalShelter4 pull request #2
Opened 2022-12-28 14:29 UTC by FetisovDen

Added a database and entities

2022-12-28 19:09 UTC, SlavZ27 requested changes
Прошу поправить

2022-12-29 05:38 UTC, FetisovDen commented on src/main/java/pro/sky/animalshelter4/entity/City.java
> +@Entity(name = "city")
+

2022-12-29 05:38 UTC, FetisovDen commented on src/main/java/pro/sky/animalshelter4/entity/NeedFinishRequestClient.java
> +    @Id
поправки внес

2022-12-29 05:38 UTC, FetisovDen commented on src/main/resources/liquibase/scripts/index.sql
> +    name             TEXT        NOT NULL,
поправки внес

2022-12-29 05:39 UTC, FetisovDen commented on src/main/resources/liquibase/scripts/index.sql
> +    name             TEXT        NOT NULL,
поправки внес

2022-12-29 05:39 UTC, FetisovDen commented on src/main/resources/liquibase/scripts/index.sql
> +    is_open               BOOLEAN DEFAULT FALSE,
поправки внес

2022-12-29 05:39 UTC, FetisovDen commented on src/main/resources/liquibase/scripts/index.sql
> +    local_date_time_close TIMESTAMP NOT NULL
поправки внес

2022-12-29 05:39 UTC, FetisovDen commented on src/main/resources/liquibase/scripts/index.sql
> +    time_zone   INT,
поправки внес

2022-12-29 05:39 UTC, FetisovDen commented on src/main/resources/liquibase/scripts/index.sql
> +    is_open               BOOLEAN DEFAULT FALSE,
поправки внес

2022-12-29 05:39 UTC, FetisovDen commented on src/main/resources/liquibase/scripts/index.sql
> +    local_date_time_close TIMESTAMP NOT NULL
поправки внес

2022-12-29 05:39 UTC, FetisovDen commented on src/main/resources/liquibase/scripts/index.sql
> +    id_client BIGINT REFERENCES client (id),
поправки внес

2022-12-29 05:39 UTC, FetisovDen commented on src/main/resources/liquibase/scripts/index.sql
> +    id_volunteer BIGINT REFERENCES volunteer (id),
поправки внес

2022-12-29 05:41 UTC, FetisovDen commented
Посмотри еще pom файлик плиз, если не глядел,  его тож менял

2022-12-29 06:01 UTC, SlavZ27 approved these changes
All ok

2022-12-29 06:12 UTC, SlavZ27 commented
мердж в мастер. нужно в dev

2022-12-29 06:12 UTC, closed without merging